insert into companies (
    name, 
    slug, 
    description, 
    website, 
    specializations, 
    business_email, 
    phone_number, 
    logo, 
    tagline, 
    employees_count, 
    country, 
    state, 
    year_founded
) 
values
(
    'Mashup Garage', 
    'mashup-garage', 
    'We are a creative software development agency specialising in AI, SaaS Development, UI/UX, and digital experiences that drive business growth.',
    'https://www.mashupgarage.com/', 
    '{"Software Development", "IT"}', 
    'hello@mashupgarage.com', 
    '1234567890', 
    'https://www.mashupgarage.com/logo-mono.svg', 
    'Award-winning software agency creating innovative solutions that drive business growth and user engagement.', 
    '50-100',
    'Philippines', 
    'Manila', 
    2017
),
(
    'Accenture', 
    'accenture', 
    'Accenture embraces the power of change to create 360° value and shared success for our clients, people, shareholders, partners and communities.', 
    'https://www.accenture.com/ph-en/about/contact-us', 
    '{"Cybersecurity", "Consulting", "Data Science"}', 
    'business_email_2', 
    '09123456789', 
    'https://logos-world.net/wp-content/uploads/2020/06/Accenture-Emblem.png', 
    'Let there be change.', 
    '10000+', 
    'India', 
    'Delhi', 
    1989
),
(
    'Sprout Solutions', 
    'sprout-solutions', 
    'Sprout is a leading provider of HR and payroll software in the Philippines, helping businesses automate their people operations.', 
    'https://sprout.ph', 
    '{"HR Tech", "SaaS"}', 
    'info@sprout.ph', 
    '09234567890', 
    'https://sprout.ph/logo.svg', 
    'Revolutionizing HR and Payroll in the Philippines.', 
    '200-500', 
    'Philippines', 
    'Makati', 
    2015
),
(
    'Thinking Machines', 
    'thinking-machines', 
    'We help organizations use data to make better decisions through AI, data science, and analytics consulting.', 
    'https://thinkingmachin.es', 
    '{"AI", "Data Science", "Analytics"}', 
    'hello@thinkingmachin.es', 
    '09111222333', 
    'https://thinkingmachin.es/logo.png', 
    'AI and Data for smarter decisions.', 
    '50-100', 
    'Philippines', 
    'Taguig', 
    2015
),
(
    '8layer Technologies', 
    '8layer-technologies', 
    'A homegrown open source software and hardware company providing innovative solutions for the public and private sector.', 
    'https://8layertech.com', 
    '{"Open Source", "IoT", "Custom Software"}', 
    'connect@8layertech.com', 
    '09999888777', 
    'https://8layertech.com/logo.png', 
    'Open source, open mind.', 
    '10-50', 
    'Philippines', 
    'Quezon City', 
    2005
);
